const foods = [
  // =========================================================
  // GRAINS / CARBOHYDRATES
  // =========================================================

  {
    id: "white_rice",
    name: "White Rice",
    category: "grain",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "brown_rice",
    name: "Brown Rice",
    category: "grain",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 123,
    protein: 2.7,
    carbs: 25.6,
    fats: 1,
    budget: "medium",
    meals: ["lunch", "dinner"],
  },

  {
    id: "roti",
    name: "Roti",
    category: "grain",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 100,
    protein: 3,
    carbs: 18,
    fats: 2,
    budget: "low",
    meals: ["breakfast", "lunch", "dinner"],
  },

  {
    id: "multigrain_roti",
    name: "Multigrain Roti",
    category: "grain",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 110,
    protein: 3.5,
    carbs: 19,
    fats: 2,
    budget: "low",
    meals: ["breakfast", "lunch", "dinner"],
  },

  {
    id: "paratha",
    name: "Home-style Paratha",
    category: "grain",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 180,
    protein: 4,
    carbs: 25,
    fats: 7,
    budget: "low",
    meals: ["breakfast"],
  },

  {
    id: "oats",
    name: "Oats",
    category: "grain",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fats: 6.9,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  {
    id: "dalia",
    name: "Dalia",
    category: "grain",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 342,
    protein: 12,
    carbs: 76,
    fats: 1.3,
    budget: "low",
    meals: ["breakfast", "dinner"],
  },

  {
    id: "poha",
    name: "Poha",
    category: "grain",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 110,
    protein: 2,
    carbs: 23,
    fats: 1,
    budget: "low",
    meals: ["breakfast"],
  },

  {
    id: "upma",
    name: "Upma",
    category: "grain",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 150,
    protein: 4,
    carbs: 25,
    fats: 4,
    budget: "low",
    meals: ["breakfast"],
  },

  {
    id: "idli",
    name: "Idli",
    category: "grain",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 58,
    protein: 2,
    carbs: 12,
    fats: 0.4,
    budget: "low",
    meals: ["breakfast"],
  },

  {
    id: "dosa",
    name: "Plain Dosa",
    category: "grain",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 130,
    protein: 3,
    carbs: 22,
    fats: 3,
    budget: "low",
    meals: ["breakfast"],
  },

  {
    id: "besan_chilla",
    name: "Besan Chilla",
    category: "grain",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 120,
    protein: 6,
    carbs: 15,
    fats: 4,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  {
    id: "khichdi",
    name: "Dal Khichdi",
    category: "grain",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 120,
    protein: 4,
    carbs: 20,
    fats: 3,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  // =========================================================
  // DAL / LEGUMES / PLANT PROTEIN
  // =========================================================

  {
    id: "toor_dal",
    name: "Toor Dal",
    category: "dal",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 116,
    protein: 7,
    carbs: 20,
    fats: 0.4,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "moong_dal",
    name: "Moong Dal",
    category: "dal",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 105,
    protein: 7,
    carbs: 19,
    fats: 0.4,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "masoor_dal",
    name: "Masoor Dal",
    category: "dal",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 116,
    protein: 9,
    carbs: 20,
    fats: 0.4,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "urad_dal",
    name: "Urad Dal",
    category: "dal",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 116,
    protein: 7,
    carbs: 20,
    fats: 0.5,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "chana_dal",
    name: "Chana Dal",
    category: "dal",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 120,
    protein: 7,
    carbs: 20,
    fats: 2,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "mixed_dal",
    name: "Mixed Dal",
    category: "dal",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 115,
    protein: 7,
    carbs: 19,
    fats: 1,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "rajma",
    name: "Rajma",
    category: "legume",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 127,
    protein: 8.7,
    carbs: 22.8,
    fats: 0.5,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "black_chana",
    name: "Black Chana",
    category: "legume",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fats: 2.6,
    budget: "low",
    meals: ["breakfast", "lunch", "snack"],
  },

  {
    id: "kabuli_chana",
    name: "Kabuli Chana",
    category: "legume",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fats: 2.6,
    budget: "low",
    meals: ["lunch", "snack"],
  },

  {
    id: "green_peas",
    name: "Green Peas",
    category: "legume",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 81,
    protein: 5.4,
    carbs: 14.5,
    fats: 0.4,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "soy_chunks",
    name: "Soy Chunks",
    category: "plant_protein",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 345,
    protein: 52,
    carbs: 33,
    fats: 0.5,
    budget: "low",
    meals: ["lunch", "dinner", "snack"],
  },

  {
    id: "sattu",
    name: "Sattu",
    category: "plant_protein",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 380,
    protein: 20,
    carbs: 58,
    fats: 7,
    budget: "low",
    meals: ["breakfast", "snack", "pre_workout"],
  },

  // =========================================================
  // DAIRY
  // =========================================================

  {
    id: "milk",
    name: "Milk",
    category: "dairy",
    type: "vegetarian",
    servingUnit: "ml",
    servingSize: 250,
    calories: 150,
    protein: 8,
    carbs: 12,
    fats: 8,
    budget: "low",
    meals: ["breakfast", "snack", "post_workout"],
  },

  {
    id: "low_fat_milk",
    name: "Low-Fat Milk",
    category: "dairy",
    type: "vegetarian",
    servingUnit: "ml",
    servingSize: 250,
    calories: 110,
    protein: 8,
    carbs: 12,
    fats: 3,
    budget: "low",
    meals: ["breakfast", "snack", "post_workout"],
  },

  {
    id: "curd",
    name: "Curd",
    category: "dairy",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 60,
    protein: 3.5,
    carbs: 4.5,
    fats: 3,
    budget: "low",
    meals: ["breakfast", "lunch", "snack", "dinner"],
  },

  {
    id: "buttermilk",
    name: "Buttermilk",
    category: "dairy",
    type: "vegetarian",
    servingUnit: "ml",
    servingSize: 250,
    calories: 60,
    protein: 3,
    carbs: 5,
    fats: 2,
    budget: "low",
    meals: ["lunch", "snack"],
  },

  {
    id: "paneer",
    name: "Paneer",
    category: "dairy_protein",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 265,
    protein: 18,
    carbs: 6,
    fats: 20,
    budget: "medium",
    meals: ["lunch", "dinner", "snack"],
  },

  {
    id: "low_fat_paneer",
    name: "Low-Fat Paneer",
    category: "dairy_protein",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 170,
    protein: 25,
    carbs: 5,
    fats: 7,
    budget: "medium",
    meals: ["lunch", "dinner"],
  },

  // =========================================================
  // EGGS
  // =========================================================

  {
    id: "whole_egg",
    name: "Whole Egg",
    category: "egg",
    type: "non_vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 70,
    protein: 6.3,
    carbs: 0.4,
    fats: 4.8,
    budget: "low",
    meals: [
      "breakfast",
      "snack",
      "post_workout",
    ],
  },

  {
    id: "egg_white",
    name: "Egg White",
    category: "egg",
    type: "non_vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 17,
    protein: 3.6,
    carbs: 0.2,
    fats: 0.1,
    budget: "low",
    meals: [
      "breakfast",
      "post_workout",
    ],
  },

  {
    id: "egg_bhurji",
    name: "Egg Bhurji",
    category: "egg",
    type: "non_vegetarian",
    servingUnit: "piece",
    servingSize: 2,
    calories: 180,
    protein: 13,
    carbs: 3,
    fats: 12,
    budget: "low",
    meals: ["breakfast", "dinner"],
  },

  {
    id: "omelette",
    name: "Omelette",
    category: "egg",
    type: "non_vegetarian",
    servingUnit: "piece",
    servingSize: 2,
    calories: 180,
    protein: 13,
    carbs: 3,
    fats: 12,
    budget: "low",
    meals: ["breakfast"],
  },

  // =========================================================
  // CHICKEN
  // =========================================================

  {
    id: "chicken_breast",
    name: "Chicken Breast",
    category: "chicken",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    budget: "medium",
    meals: [
      "lunch",
      "dinner",
      "post_workout",
    ],
  },

  {
    id: "home_style_chicken_curry",
    name: "Home-style Chicken Curry",
    category: "chicken",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 190,
    protein: 20,
    carbs: 5,
    fats: 10,
    budget: "medium",
    meals: ["lunch", "dinner"],
  },

  {
    id: "grilled_chicken",
    name: "Grilled Chicken",
    category: "chicken",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    budget: "medium",
    meals: [
      "lunch",
      "dinner",
      "post_workout",
    ],
  },

  {
    id: "chicken_rice_bowl",
    name: "Chicken Rice Bowl",
    category: "chicken",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 160,
    protein: 8,
    carbs: 20,
    fats: 5,
    budget: "medium",
    meals: ["lunch", "dinner"],
  },

  // =========================================================
  // FISH
  // =========================================================

  {
    id: "rohu",
    name: "Rohu Fish",
    category: "fish",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 97,
    protein: 18,
    carbs: 0,
    fats: 2,
    budget: "medium",
    meals: ["lunch", "dinner"],
  },

  {
    id: "katla",
    name: "Katla Fish",
    category: "fish",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 100,
    protein: 18,
    carbs: 0,
    fats: 3,
    budget: "medium",
    meals: ["lunch", "dinner"],
  },

  {
    id: "fish_curry",
    name: "Home-style Fish Curry",
    category: "fish",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 140,
    protein: 18,
    carbs: 4,
    fats: 6,
    budget: "medium",
    meals: ["lunch", "dinner"],
  },

  // =========================================================
  // OTHER NON-VEGETARIAN
  // =========================================================

  {
    id: "chicken_liver",
    name: "Chicken Liver",
    category: "organ_meat",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 135,
    protein: 20,
    carbs: 1,
    fats: 5,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "lean_mutton",
    name: "Lean Mutton",
    category: "mutton",
    type: "non_vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 250,
    protein: 25,
    carbs: 0,
    fats: 16,
    budget: "high",
    meals: ["lunch", "dinner"],
  },

  // =========================================================
  // FRUITS
  // =========================================================

  {
    id: "banana",
    name: "Banana",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.3,
    budget: "low",
    meals: [
      "breakfast",
      "snack",
      "pre_workout",
      "post_workout",
    ],
  },

  {
    id: "apple",
    name: "Apple",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fats: 0.3,
    budget: "medium",
    meals: ["breakfast", "snack"],
  },

  {
    id: "guava",
    name: "Guava",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 68,
    protein: 2.5,
    carbs: 14,
    fats: 1,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  {
    id: "papaya",
    name: "Papaya",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fats: 0.3,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  {
    id: "orange",
    name: "Orange",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 62,
    protein: 1.2,
    carbs: 15,
    fats: 0.2,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  {
    id: "sweet_lime",
    name: "Sweet Lime",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 50,
    protein: 1,
    carbs: 13,
    fats: 0.2,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  {
    id: "watermelon",
    name: "Watermelon",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fats: 0.2,
    budget: "low",
    meals: ["snack"],
  },

  {
    id: "muskmelon",
    name: "Muskmelon",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 34,
    protein: 0.8,
    carbs: 8,
    fats: 0.2,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  {
    id: "mango",
    name: "Mango",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fats: 0.4,
    budget: "medium",
    meals: ["breakfast", "snack"],
  },

  {
    id: "pomegranate",
    name: "Pomegranate",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 83,
    protein: 1.7,
    carbs: 19,
    fats: 1.2,
    budget: "high",
    meals: ["breakfast", "snack"],
  },

  {
    id: "pear",
    name: "Pear",
    category: "fruit",
    type: "vegetarian",
    servingUnit: "piece",
    servingSize: 1,
    calories: 100,
    protein: 0.6,
    carbs: 27,
    fats: 0.2,
    budget: "medium",
    meals: ["breakfast", "snack"],
  },

  // =========================================================
  // VEGETABLES
  // =========================================================

  {
    id: "potato",
    name: "Potato",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 77,
    protein: 2,
    carbs: 17,
    fats: 0.1,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "sweet_potato",
    name: "Sweet Potato",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fats: 0.1,
    budget: "low",
    meals: ["breakfast", "snack", "pre_workout"],
  },

  {
    id: "spinach",
    name: "Spinach",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fats: 0.4,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "cauliflower",
    name: "Cauliflower",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fats: 0.3,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "cabbage",
    name: "Cabbage",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 25,
    protein: 1.3,
    carbs: 6,
    fats: 0.1,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "carrot",
    name: "Carrot",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fats: 0.2,
    budget: "low",
    meals: ["lunch", "dinner", "snack"],
  },

  {
    id: "tomato",
    name: "Tomato",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fats: 0.2,
    budget: "low",
    meals: ["breakfast", "lunch", "dinner"],
  },

  {
    id: "cucumber",
    name: "Cucumber",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fats: 0.1,
    budget: "low",
    meals: ["lunch", "dinner", "snack"],
  },

  {
    id: "lauki",
    name: "Lauki",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 15,
    protein: 0.6,
    carbs: 3.4,
    fats: 0.1,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "bhindi",
    name: "Bhindi",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 33,
    protein: 1.9,
    carbs: 7.5,
    fats: 0.2,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  {
    id: "mixed_vegetables",
    name: "Mixed Vegetables",
    category: "vegetable",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 70,
    protein: 3,
    carbs: 12,
    fats: 1.5,
    budget: "low",
    meals: ["lunch", "dinner"],
  },

  // =========================================================
  // NUTS / SEEDS
  // =========================================================

  {
    id: "peanuts",
    name: "Peanuts",
    category: "nuts",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 567,
    protein: 25.8,
    carbs: 16.1,
    fats: 49.2,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  {
    id: "almonds",
    name: "Almonds",
    category: "nuts",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fats: 49.9,
    budget: "medium",
    meals: ["breakfast", "snack"],
  },

  {
    id: "walnuts",
    name: "Walnuts",
    category: "nuts",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fats: 65.2,
    budget: "high",
    meals: ["breakfast", "snack"],
  },

  {
    id: "flax_seeds",
    name: "Flax Seeds",
    category: "seed",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 534,
    protein: 18.3,
    carbs: 28.9,
    fats: 42.2,
    budget: "low",
    meals: ["breakfast", "snack"],
  },

  // =========================================================
  // OILS
  // =========================================================

  {
    id: "mustard_oil",
    name: "Mustard Oil",
    category: "oil",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 884,
    protein: 0,
    carbs: 0,
    fats: 100,
    budget: "low",
    meals: [
      "breakfast",
      "lunch",
      "dinner",
    ],
  },

  {
    id: "groundnut_oil",
    name: "Groundnut Oil",
    category: "oil",
    type: "vegetarian",
    servingUnit: "gram",
    servingSize: 100,
    calories: 884,
    protein: 0,
    carbs: 0,
    fats: 100,
    budget: "low",
    meals: [
      "breakfast",
      "lunch",
      "dinner",
    ],
  },

  // =========================================================
  // DRINKS
  // =========================================================

  {
    id: "lemon_water",
    name: "Lemon Water",
    category: "drink",
    type: "vegetarian",
    servingUnit: "ml",
    servingSize: 250,
    calories: 8,
    protein: 0.2,
    carbs: 2,
    fats: 0,
    budget: "low",
    meals: [
      "breakfast",
      "snack",
      "pre_workout",
    ],
  },

  {
    id: "coconut_water",
    name: "Coconut Water",
    category: "drink",
    type: "vegetarian",
    servingUnit: "ml",
    servingSize: 250,
    calories: 45,
    protein: 2,
    carbs: 9,
    fats: 0,
    budget: "medium",
    meals: ["snack", "post_workout"],
  },

  {
    id: "water",
    name: "Water",
    category: "drink",
    type: "vegetarian",
    servingUnit: "ml",
    servingSize: 250,
    calories: 0,
    protein: 0,
    carbs: 0,
    fats: 0,
    budget: "low",
    meals: [
      "breakfast",
      "lunch",
      "snack",
      "dinner",
    ],
  },
];

export default foods;